sudo: required

language: node_js

node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"

before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository --yes ppa:dhor/myway
  - sudo apt-get -qq update
  - sudo apt-get install graphicsmagick

install:
  - npm install

script:
  - nvm use 8
  - npm run build
  - nvm use $TRAVIS_NODE_VERSION
  - npm test
  - nvm use 8
  - npm run preversion
